### ISSUE TITLE
Design Notes March 3

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/text-editor#110]
## Login page
- [x] Bigger
- [x] White box on the right should be height 100%
- [x] Responsive layouts: wide https://projects.invisionapp.com/d/main#/console/17925240/409452614/preview narrow https://projects.invisionapp.com/d/main#/console/17925240/409455403/preview

## Indexes 
**General**
- [x] Clicking back or on the breadcrumb should remember the page in the index the user was on (that is, in this example the list of subjects should be on page 4)
- [x] User dropdown needs more padding around items – should be 44px tall

**Search/Filter**
- [x] Dropdown arrow should be black
- [x] Checkboxes look like they've been stretched? 
- [x] Checkboxes also shouldn't be teal

## Transcribe viewer 
**Main Interface**
- [x] Use Karla Regular (300?) instead of bold (600) for the subject name
- [x] Is there an outline version of the metadata icon? It's quite heavy
- [x] Mark as Approved toggle stroke is too thick, should just be 1px
- [x] Add a checkbox inside the Mark as Approved toggle when the subject has been approved (accessibility)
- [x] Undo icon needs to be a little larger to match the other icons
- [x] All the up/down arrows (More dropdown, etc) need to be reversed so their default state is pointing down
- [x] Original Subject, Transcribed Text, and All Pages labels should be 18px

**Original Subject**
- [x] Zoom controls should have a white background with 50% opacity
- [x] (Change from InVision) Swap zoom controls so Zoom Out is on the far left 
- [x] Clicking on a line in the original subject should highlight the corresponding transcribed line ("As an admin I want to click on a line and view that line’s consensus transcription as well as a grid showing individual (raw) transcriptions.") (#112)
- [x] Switch open and closed circles on lines: in the FER transcriptions we're doing open circles for the start of a line, closed for the end (#105)

**Transcribed Lines** 
- [x] Add some space between `Flag` and `Consensus Score`
- [x] Smaller drag handles on each line

**Transcribed Line Detail**
- [x] Remove the bullet from transcribed details (eg Anonymous)
- [x] Text input should be taller
~- [ ] Clicking anywhere outside the line should close the modal~ 
- [x] Other buttons (toolbar for example) should be disabled while modal is open

**All Pages section**
- [x] Capitalize `p` in `Pages`
- [x] Thumbnails need a hover state
- [x] Let's use the teal as the selected outline since teal is used in the pagination circles

**Comment by wgranger** [comment]
@beckyrother
Few questions:

**Login Page**
- What needs to be bigger?
- What does "more tk" mean?

**Main Interface**
- The checkbox inside the mark as approved toggle. Is this an "x" or check depending on the state?

**Transcribed Line Detail**
- This is completed in another PR, so the bullets make more sense when the design is complete. However, do you still want it to read (June 11, 2018 16:22 usename) without a bullet?

**All Pages section**
- What should the hover state look like?

**Comment by beckyrother** [comment]
***Login Page***
- bigger type:
   - Aggregate Line Inspector: 32px
   - bigger logos (should all be 50px tall)
- more tk = more to come:
   - the provided design didn't account for different screen sizes, i'll upload some variations

***Main interface***
- yes please

***transcribed line detail***
- yes, please remove the bullet

**Comment by wgranger** [comment]
@beckyrother 
One more question:

**Transcribed Line Detail**
- Clicking anywhere outside the line should close the modal

Does this mean that clicking anything outside the transcription _modal_ should close the modal?  If so, by default, all toolbar items would be "disabled" since clicking them would only result in closing the modal.

**Comment by beckyrother** [comment]
Yes, that's correct

**Comment by beckyrother** [comment]
Updated the original to remove `more tk` and add the responsive widths for the home page. 

We also decided not to allow clicking outside the modal to close it, but will still disable everything outside the modal while it's open.

**Comment by wgranger** [comment]
So all buttons should be disabled when a transcription is open. Does this include the undo button? The undo button tracks changes on the editor page. Currently, if you open the transcription modal, you can press the undo button to close that modal again. 

Let's say we disable all buttons, including undo, when that modal opens. That means we would:
 - Make a bunch of text changes and rearrange some lines
 - Select a transcription to open the modal
 - Close that modal
 - If we then press the undo button, we our only able to ever go back to that last step where the modal was open since the ability to press the undo button again is disabled.

Because of this, we should either:
**A:** Keep the undo button from disabling so we can continue undoing steps
**B:** Keep opening/closing the modal from being a part of the undo tracking

I can also share screens for a video walkthrough if this is still unclear.

**Comment by beckyrother** [comment]
Thanks Will! Good to point out. Let's keep the undo button active so you can step back more gradually, and do `B` as well.
